# Generated by Django 3.0.8 on 2020-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_cost', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RareMetalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('PA', 'PALLADIUM'), ('RU', 'RUTHENIUM'), ('PL', 'PLATINUM'), ('IR', 'IRIDIUM'), ('RO', 'RHODIUM')], max_length=2)),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('HK', 'HONG_KONG'), ('LO', 'LONDON'), ('NY', 'NEW_YORK')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RareMetalSupplyAndDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField()),
                ('Total_Supply', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Total_Demand', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Recycling', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Net_Demand', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Movements', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(choices=[('SA', 'South Africa'), ('RU', 'Russia'), ('RP', 'Russia Primary'), ('RS', 'Russia Stock Sales'), ('NA', 'North_America'), ('ZI', 'Zimbabwe'), ('OT', 'Others')], max_length=2)),
            ],
        ),
    ]
